### ISSUE TITLE
All field names of RoadNetwork do not follow encoding rules. To resolve this issue, we need to define `LogicFile`, `SceneGraphFile` and `TrafficSignals`.

### ISSUE THREAD

**Issue by hcn1519** [hcn1519/ADS-scenario-transfer#25]
`RoadNetwork` breaks encoding rules. 

- [x] To make it following original rules, we need to define `LogicFile`, `SceneGraphFile`, and `TrafficSignals`.

`RoadNetwork` message looks like this.

```proto
message RoadNetwork {
    optional File logicFile = 1;  // 0..1
    optional File sceneGraphFile = 2;  // 0..1
    optional TrafficSignalController trafficSignals = 3;  // 0..*
}
```

It should generate yaml like:

```yaml
RoadNetwork:
  File:
    filepath: path
  File:
    filepath: path
  ...
```
As you can see, there is a name conflicting between logicFile and sceneGraphFile. It causes hard to apply all of them. And, `RoadNetwork` in real-world scenario's looks like below. 

```yaml
RoadNetwork:
    LogicFile:
      filepath: awf_cicd_virtual_E_dev.osm
    SceneGraphFile:
      filepath: awf_cicd_virtual_E_dev.pcd
    TrafficSignals:
      TrafficSignalController:
        - name: StraghtSignal
          Phase:
            - name: RED
              duration: INF
              TrafficSignalState:
                - trafficSignalId: '12515'
                  state: red solidOn circle
                - trafficSignalId: '12526'
                  state: green solidOn circle
            - name: GREEN
              duration: INF
              TrafficSignalState:
                - trafficSignalId: '12515'
                  state: green solidOn circle
                - trafficSignalId: '12526'
                  state: red solidOn circle
```
